tasks:
  - init: |
      cd ~
      curl -fL https://github.com/coursier/launchers/raw/master/cs-x86_64-pc-linux.gz | gzip -d > cs
      chmod +x cs
      yes | ./cs setup
      export PATH="$PATH:~/.local/share/coursier/bin"
      cd /workspace/VyxalS
  - command: |
      sbt
