name: Text and MD doc gen

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  generate:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Generate documentation
        run: sbt yaml/run
      - name: Stage changes
        run: git add .
      - name: Commit and push
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Generate MD and text documentation"
